### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by devicenull** [RIPE-NCC/rpki-validator-3#54]
This is on a machine with 4GB of memory, and no swap.  Do I need to add swap space here?  What sort of memory usage should I expect?

It seems that memory usage just grows with uptime, which seems to suggest a leak to me.

```Nov 25 02:24:06 rpki1 rpki-validator-3.sh[31121]: 2018-11-25 02:21:35,642 #011 WARN  #011 rpki housekeeper #011#011#011 c.z.h.p.HikariPool #011#011 rpki - Thread starvation or clock leap detected (housekeeper delta=54s456ms418µs793ns).
Nov 25 02:30:55 rpki1 rpki-validator-3.sh[31121]: 2018-11-25 02:30:31,097 #011 WARN  #011 rpki housekeeper #011#011#011 c.z.h.p.HikariPool #011#011 rpki - Thread starvation or clock leap detected (housekeeper delta=6m20s188ms117µs929ns).
Nov 25 02:32:38 rpki1 rpki-validator-3.sh[31121]: 2018-11-25 02:32:04,226 #011 WARN  #011 rpki housekeeper #011#011#011 c.z.h.p.HikariPool #011#011 rpki - Thread starvation or clock leap detected (housekeeper delta=5m38s672ms755µs943ns).
Nov 25 02:36:36 rpki1 rpki-validator-3.sh[31121]: 2018-11-25 02:33:31,672 #011 WARN  #011 rpki housekeeper #011#011#011 c.z.h.p.HikariPool #011#011 rpki - Thread starvation or clock leap detected (housekeeper delta=1m41s264ms38µs59ns).
Nov 25 02:38:49 rpki1 rpki-validator-3.sh[31121]: Exception in thread "http-nio-127.0.0.1-8080-Acceptor-0"
Nov 25 02:38:49 rpki1 rpki-validator-3.sh[31121]: Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-nio-127.0.0.1-8080-exec-6"
Nov 25 02:39:19 rpki1 rpki-validator-3.sh[31121]: java.lang.OutOfMemoryError: Java heap space
Nov 25 02:40:08 rpki1 rpki-validator-3.sh[31121]: Exception in thread "http-nio-127.0.0.1-8080-exec-1" java.lang.OutOfMemoryError: Java heap space
Nov 25 02:45:07 rpki1 rpki-validator-3.sh[31121]: Exception in thread "http-nio-127.0.0.1-8080-exec-7" java.lang.OutOfMemoryError: Java heap space
Nov 25 02:47:42 rpki1 rpki-validator-3.sh[31121]: Exception in thread "http-nio-127.0.0.1-8080-exec-4" Exception in thread "http-nio-127.0.0.1-8080-exec-9" java.lang.OutOfMemoryError: Java heap space
Nov 25 02:47:42 rpki1 rpki-validator-3.sh[31121]: java.lang.OutOfMemoryError: Java heap space
Nov 25 02:47:42 rpki1 rpki-validator-3.sh[31121]: Exception in thread "http-nio-127.0.0.1-8080-exec-10" java.lang.OutOfMemoryError: Java heap space
Nov 25 02:47:43 rpki1 rpki-validator-3.sh[31121]: Exception in thread "http-nio-127.0.0.1-8080-exec-5" java.lang.OutOfMemoryError: Java heap space
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: 2018-11-25 02:41:59,225 #011 ERROR #011 QuartzScheduler_quartzScheduler-NON_CLUSTERED_MisfireHandler #011#011#011 o.s.s.q.LocalDataSourceJobStore #011#011 MisfireHandler: Error handling misfires: Failure obtaining db row lock: Timeout trying to lock table ; SQL statement:
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME = ? FOR UPDATE [50200-197]
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Timeout trying to lock table ; SQL statement:
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME = ? FOR UPDATE [50200-197]
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:157)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3247)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3997)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4018)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: Caused by: org.h2.jdbc.JdbcSQLException: Timeout trying to lock table ; SQL statement:
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME = ? FOR UPDATE [50200-197]
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.message.DbException.get(DbException.java:168)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.command.Command.filterConcurrentUpdate(Command.java:316)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.command.Command.executeQuery(Command.java:206)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:96)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: ... 4 common frames omitted
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: Caused by: org.h2.jdbc.JdbcSQLException: Concurrent update in table "QRTZ_LOCKS": another transaction has updated or deleted the same row [90131-197]
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.message.DbException.get(DbException.java:168)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.mvstore.db.MVTable.convertException(MVTable.java:922)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.mvstore.db.MVSecondaryIndex.remove(MVSecondaryIndex.java:252)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.mvstore.db.MVTable.removeRow(MVTable.java:706)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.table.TableFilter.lockRows(TableFilter.java:1163)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.command.dml.Select.queryFlat(Select.java:538)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.command.dml.Select.queryWithoutCache(Select.java:633)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.command.dml.Query.query(Query.java:371)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.command.dml.Query.query(Query.java:333)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.command.CommandContainer.query(CommandContainer.java:114)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.command.Command.executeQuery(Command.java:202)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: ... 8 common frames omitted
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: Caused by: java.lang.IllegalStateException: Entry is locked [1.4.197/101]
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.mvstore.db.TransactionStore$TransactionMap.set(TransactionStore.java:1067)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.mvstore.db.TransactionStore$TransactionMap.remove(TransactionStore.java:1026)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: at org.h2.mvstore.db.MVSecondaryIndex.remove(MVSecondaryIndex.java:246)
Nov 25 02:52:52 rpki1 rpki-validator-3.sh[31121]: ... 17 common frames omitted
Nov 25 03:04:45 rpki1 rpki-validator-3.sh[31121]: 2018-11-25 03:04:45,892 #011 WARN  #011 quartzScheduler_Worker-2 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 90108, SQLState: 90108
Nov 25 03:04:45 rpki1 rpki-validator-3.sh[31121]: 2018-11-25 03:04:45,892 #011 ERROR #011 quartzScheduler_Worker-2 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 Out of memory.; SQL statement:
Nov 25 03:04:45 rpki1 rpki-validator-3.sh[31121]: /* select rpkiObject
Nov 25 03:04:45 rpki1 rpki-validator-3.sh[31121]: from RpkiObject rpkiObject
Nov 25 03:04:45 rpki1 rpki-validator-3.sh[31121]: where rpkiObject.sha256 = (?1) */ select rpkiobject0_.id as id1_5_, rpkiobject0_.created_at as created_2_5_, rpkiobject0_.updated_at as updated_3_5_, rpkiobject0_.version as version4_5_, rpkiobject0_.authority_key_identifier as authorit5_5_, rpkiobject0_.last_marked_reachable_at as last_mar6_5_, rpkiobject0_.serial_number as serial_n7_5_, rpkiobject0_.sha256 as sha8_5_, rpkiobject0_.signing_time as signing_9_5_, rpkiobject0_.type as type10_5_ from rpki_object rpkiobject0_ where rpkiobject0_.sha256=? [90108-197]
Nov 25 03:04:45 rpki1 rpki-validator-3.sh[31121]: 2018-11-25 03:04:45,895 #011 ERROR #011 quartzScheduler_Worker-4 #011#011#011 o.s.o.j.JpaTransactionManager #011#011 Commit exception overridden by rollback exception
Nov 25 03:04:45 rpki1 rpki-validator-3.sh[31121]: java.lang.OutOfMemoryError: Java heap space
Nov 25 03:04:45 rpki1 rpki-validator-3.sh[31121]: 2018-11-25 03:04:45,897 #011 ERROR #011 quartzScheduler_QuartzSchedulerThread #011#011#011 o.s.s.q.LocalDataSourceJobStore #011#011 Couldn't rollback jdbc connection. The database has been closed [90098-197]
Nov 25 03:04:45 rpki1 rpki-validator-3.sh[31121]: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
````

**Comment by dacruz** [comment]
We're going to investigate the issue.

**Comment by lolepezy** [comment]
Could you try the latest build to see if you still have the same problem? We made quite a lot of memory-related optimisations, so the issue will probably go away.
