### ISSUE TITLE
high cpu, java IO exception 3.0-333

### ISSUE THREAD

**Issue by cwiech** [RIPE-NCC/rpki-validator-3#63]
I am running 3.0-333, I have a problem when I add a lot of clients. Good behavior is the CPU spikes for a bit, and then calms down, but if I add/remove clients  (emulating startup/flapping in the network), the sessions are up, and there is no network traffic, but the CPU's are maxed. Usually after a couple of these on the console. The sessions stay up, but the CPU then goes down. Its like its getting stuck on something and eventually gets past it.

I am testing wtih 100-400 gobgp sessions. It seems less about the number and more about the state changes.

 WARN 8433 --- [tLoopGroup-3-16] i.n.c.AbstractChannelHandlerContext      : An exception '{}' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_191]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_191]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-buffer-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345) ~[netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126) ~[netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.19.Final.jar!/:4.1.19.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

2019-01-15 13:02:26.095  WARN 8433 --- [tLoopGroup-3-28] i.n.c.AbstractChannelHandlerContext      : An exception '{}' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_191]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_191]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-buffer-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345) ~[netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126) ~[netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.19.Final.jar!/:4.1.19.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.19.Final.jar!/:4.1.19.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

**Comment by cwiech** [comment]
I am using this software package (it’s the only one I found that supports rpki… ). I create a docker image with it, and then I pass in a config directory with the rpki config. Then I make 200 of them and turn them up as needed to stress the code. NOTE that the as/router-id aren’t used for RPKI, so every docker can share the same config file. Docker starts up with a different source port.. letting a single server emulate hundreds of different router sessions.

I am happy to share my docker build with you if that would help.

https://github.com/osrg/gobgp



[global.config]

    as = 65001

    router-id = "192.168.1.1"



[[rpki-servers]]

    [rpki-servers.config]

        address = "192.168.100.20"

        port = 8282

Something like this (I have g1 – g200 spread over a couple of servers).


docker run -d --name=g1 --mount type=bind,source=/data/rpki/g1,target=/data/conf cwiech/gobgp /data/gobgpd

 -f /data/conf/gobgpd.conf

**Comment by lolepezy** [comment]
Hi,

We managed to reproduce the problem without gobgp so far and there's a build 377 where the problem is addressed. 

1) Basically, it's hard to get rid of CPU usage spikes, simply because having 200 clients connecting at the same time and each of them receiving about 70000 of RTR PDU is resource consuming. We'll look at what can be done about it, but as we can see from profiling it, most of the CPU time is spent in data-copying code, so apparently, we are pretty close to optimal situation.

2) "java.io.IOException: Connection reset by peer" means that the client (gobgp in your case) has aborted the TCP session in the middle of handshake (or some other interaction, I'm not exactly sure about it). In any case, the latest build should handle this exception.
